name: Run Google Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install GoogleTest (system package, optional)
        run: sudo apt-get update && sudo apt-get install -y libgtest-dev cmake build-essential

      - name: Configure CMake
        # Enter the right folder
        run: cd cpp && cmake -B ${{github.workspace}}/cpp/build

      - name: Build Project
        run: cd cpp && cmake --build ${{github.workspace}}/cpp/build

      - name: Run Tests
        run: cd ${{github.workspace}}/cpp/build && ctest -VV
